apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/tailscale/tailscale/main/cmd/k8s-operator/deploy/manifests/operator.yaml
  - doppler.yaml
patches:
  - patch: |
      $patch: delete
      kind: Secret
      metadata:
        name: operator-oauth
    target:
      kind: Secret
      name: operator-oauth