apiVersion: v1
kind: Service
metadata:
  name: fresh-rss
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: fresh-rss
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fresh-rss
spec:
  defaultBackend:
    service:
      name: fresh-rss
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - fresh-rss